# Generated by Django 6.1 on 2026-09-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_perfilproveedor_zonaatencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración estimada en minutos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalogo.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='usuarios.perfilproveedor')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='MultimediaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video')], max_length=10)),
                ('url_o_archivo', models.CharField(help_text='URL o ruta del archivo', max_length=255)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='catalogo.servicio')),
            ],
            options={
                'verbose_name': 'contenido multimedia',
                'verbose_name_plural': 'contenidos multimedia',
            },
        ),
        migrations.CreateModel(
            name='InsumoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('INSUMO', 'Insumo'), ('EQUIPO', 'Equipo')], default='INSUMO', max_length=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_equipos', to='catalogo.servicio')),
            ],
            options={
                'verbose_name': 'insumo o equipo',
                'verbose_name_plural': 'insumos y equipos',
            },
        ),
    ]
