# Generated by Django 5.2.17 on 2026-09-19 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('duracion', models.DurationField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='multimediaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'servicioMultimedia',
                'verbose_name_plural': 'servicioMultimedias',
            },
        ),
        migrations.CreateModel(
            name='servicioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idinsumo', models.CharField(max_length=50)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'servicioInsumo',
                'verbose_name_plural': 'servicioInsumos',
            },
        ),
    ]
