# Generated by Django 5.2.17 on 2026-09-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
