# Generated by Django 5.2.17 on 2026-09-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_creado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioinsumo',
            name='idinsumo',
        ),
    ]
