# Generated by Django 5.2.17 on 2026-09-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_remove_servicioinsumo_idinsumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimediaservicio',
            old_name='servicio',
            new_name='servicioK',
        ),
        migrations.RenameField(
            model_name='servicioinsumo',
            old_name='servicio',
            new_name='servicioK',
        ),
    ]
