# Generated by Django 5.2.17 on 2026-09-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_rename_servicio_multimediaservicio_serviciok_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimediaservicio',
            old_name='servicioK',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='servicioinsumo',
            old_name='servicioK',
            new_name='servicio',
        ),
    ]
