# Generated by Django 5.2.17 on 2026-09-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_rename_serviciok_multimediaservicio_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediaservicio',
            name='url',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
    ]
