# Generated by Django 5.2.17 on 2026-09-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_multimediaservicio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioinsumo',
            name='tipo',
            field=models.CharField(choices=[('Producto', 'producto'), ('Equipos', 'equipo'), ('Insumo', 'insumo')], default='Producto', max_length=10),
        ),
    ]
