# Generated by Django 6.1 on 2026-09-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_profesional', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('perfil_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'perfil profesional',
                'verbose_name_plural': 'perfiles profesionales',
            },
        ),
        migrations.CreateModel(
            name='ZonaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('barrio_sector', models.CharField(max_length=150)),
                ('perfil_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_atencion', to='usuarios.perfilproveedor')),
            ],
            options={
                'verbose_name': 'zona de atención',
                'verbose_name_plural': 'zonas de atención',
            },
        ),
    ]
