# Generated by Django 6.1 on 2026-09-22 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0003_perfilproveedor_zonaatencion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio_copia', models.CharField(max_length=150)),
                ('precio_copia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos_copia', models.PositiveIntegerField()),
                ('fecha_solicitada', models.DateField()),
                ('hora_solicitada', models.TimeField()),
                ('direccion_atencion', models.CharField(max_length=255)),
                ('barrio_sector', models.CharField(max_length=100)),
                ('informacion_complementaria', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SUGERIDA', 'Sugerida'), ('ACEPTADA', 'Aceptada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('motivo_rechazo_cancelacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cliente', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='usuarios.perfilproveedor')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='catalogo.servicio')),
            ],
            options={
                'verbose_name': 'solicitud o reserva',
                'verbose_name_plural': 'solicitudes y reservas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
